name: 'Playwright Tests'
on:
  workflow_call:
    secrets:
      SOME_SECRET: { required: false }

env:
  PROJECT: polkadot-migration
  NAMESPACE: polkadot
  HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  HEAD_BRANCH_NAME: ${{ github.head_ref }}

jobs:
  playwright:
    name: Playwright Shard
    runs-on: zondax-runners
    strategy:
      matrix:
        include:
          - position: shard1
            playwrightShard: '1/2'
          - position: shard2
            playwrightShard: '2/2'
    container:
      image: node:20-bookworm
      env:
        PLAYWRIGHT_SHARD: ${{ matrix.playwrightShard }}
        SOME_SECRET: ${{ secrets.SOME_SECRET }}
        CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Disable shallow clone
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Install dependencies
        run: bun install

      - name: Run build for web
        working-directory: apps/web
        run: bun run build

      - name: Install dependencies
        working-directory: apps/web
        run: bun e2e:install

      - name: Run Playwright tests
        working-directory: apps/web
        run: bun e2e:sharding

      - name: Upload Playwright Report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ matrix.position }}
          path: apps/web/playwright-report/
          retention-days: 15
