name: 'Playwright Performance Tests'
on:
  workflow_call:
    secrets:
      NEXT_PUBLIC_LOCATIONIQ_TOKEN: { required: true }
      AUTH_ZITADEL_ID: { required: true }
      AUTH_ZITADEL_SECRET: { required: true }
      AUTH_ZITADEL_ISSUER: { required: true }
      AUTH_URL: { required: true }
      AUTH_SECRET: { required: true }

      AUTH_ZITADEL_USERNAME: { required: false }
      AUTH_ZITADEL_PASSWORD: { required: false }
      DATABASE_NEON_URL: { required: false }

env:
  PROJECT: prio-next
  NAMESPACE: web-prio
  HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  HEAD_BRANCH_NAME: ${{ github.head_ref }}

jobs:
  smoke:
    name: Playwright Perf
    runs-on: zondax-runners
    strategy:
      matrix:
        shard: [1/2, 2/2]
    container:
      image: node:20-bookworm
      env:
        PLAYWRIGHT_SHARD: ${{ matrix.shard }}
        NEXT_PUBLIC_LOCATIONIQ_TOKEN: ${{ secrets.NEXT_PUBLIC_LOCATIONIQ_TOKEN }}
        NEXT_PUBLIC_GRPC_SERVER: ${{ secrets.NEXT_PUBLIC_GRPC_SERVER }}
        AUTH_ZITADEL_ID: ${{ secrets.AUTH_ZITADEL_ID }}
        AUTH_ZITADEL_SECRET: ${{ secrets.AUTH_ZITADEL_SECRET }}
        AUTH_ZITADEL_ISSUER: ${{ secrets.AUTH_ZITADEL_ISSUER }}
        AUTH_URL: ${{ secrets.AUTH_URL }}
        AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        AUTH_ZITADEL_USERNAME: ${{ secrets.AUTH_ZITADEL_USERNAME }}
        AUTH_ZITADEL_PASSWORD: ${{ secrets.AUTH_ZITADEL_PASSWORD }}
        CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Disable shallow clone
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
      - name: Install dependencies
        run: bun install

      - name: Run build for web
        working-directory: apps/web
        run: bun run build

      - name: Install dependencies
        working-directory: apps/web
        run: bun e2e:install

      - name: Run Playwright tests
        working-directory: apps/web
        run: bun e2e:perf

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/web/playwright-report/
          retention-days: 15
